const projects2 = [
  {
    name: "SOFTWARE",
    title: "GLEAM AI",
    creation: [
      { key: 1, language: "JavaScript" },
      { key: 2, language: "React JS" },
      { key: 3, language: "Next JS" },
    ],
    description: "Gleam AI es una plataforma que junta las más populares herramientas de inteligencia artificial. Utilizando las APIs de OpenAI y ReplicateAI aquí puedes encontrar todas las mejores IAs en un solo lugar.",
    colorBg: "gleamBg",
    colorTxt: "gleamTxt",
    image: "gleam cursor-pointer transition-all",
    id: 20,
    key: 3,
    float: false,
    linkP: "https://gleam-wine.vercel.app/",
    linkG: "https://github.com/Basso-23/Gleam-AI",
    modalKey: 103,
    status: "en línea",
    colorStatus: "bg-[#1ef758] glowOnline",
  },
  {
    name: "OTROS",
    title: "PORTAFOLIO",
    creation: [
      { key: 1, language: "JavaScript" },
      { key: 2, language: "React JS" },
      { key: 3, language: "Next JS" },
    ],
    description:
      "Este es mi portafolio, donde muestro todos mis proyectos y también puedes conocer más sobre mí y mis habilidades.",
    colorBg: "portfolioBg",
    colorTxt: "portfolioTxt",
    image: "portfolio cursor-pointer transition-all",
    id: 30,
    key: 1,
    float: false,
    linkP: "https://www.carlosbaso.com/",
    linkG: "https://github.com/Basso-23/Portfolio-Portafolio",
    modalKey: 101,
    status: "en línea",
    colorStatus: "bg-[#1ef758] glowOnline",
  },
  {
    name: "DISEÑO WEB",
    title: false,
    creation: [
      { key: 1, language: "JavaScript" },
      { key: 2, language: "React JS" },
      { key: 3, language: "Next JS" },
    ],
    description: [
      "Estoy trabajando duro para traer nuevos ",
      "e increíbles proyectos. ¡No puedo esperar para ",
      "desvelárselos todos pronto!",
    ],
    colorBg: "greenBg",
    colorTxt: "greenTxt",
    image: false,
    id: 10,
    key: 2,
    float: "pointer-events-none",
    linkP: false,
    linkG: false,
    modalKey: 102,
    status: false,
    colorStatus: false,
  },
  {
    name: "OTROS",
    title: false,
    creation: [
      { key: 1, language: "JavaScript" },
      { key: 2, language: "React JS" },
      { key: 3, language: "Next JS" },
    ],
    description: [
      "Estoy trabajando duro para traer nuevos ",
      "e increíbles proyectos. ¡No puedo esperar para ",
      "desvelárselos todos pronto!",
    ],
    colorBg: "yellowBg",
    colorTxt: "yellowTxt",
    image: false,
    id: 30,
    key: 4,
    float: "pointer-events-none",
    linkP: false,
    linkG: false,
    modalKey: 104,
    status: false,
    colorStatus: false,
  },
  {
    name: "DISEÑO WEB",
    title: false,
    creation: [
      { key: 1, language: "JavaScript" },
      { key: 2, language: "React JS" },
      { key: 3, language: "Next JS" },
    ],
    description: [
      "Estoy trabajando duro para traer nuevos ",
      "e increíbles proyectos. ¡No puedo esperar para ",
      "desvelárselos todos pronto!",
    ],
    colorBg: "greenBg",
    colorTxt: "greenTxt",
    image: false,
    id: 10,
    key: 5,
    float: "pointer-events-none",
    linkP: false,
    linkG: false,
    modalKey: 105,
    status: false,
    colorStatus: false,
  },
  {
    name: "SOFTWARE",
    title: false,
    creation: [
      { key: 1, language: "JavaScript" },
      { key: 2, language: "React JS" },
      { key: 3, language: "Next JS" },
    ],
    description: [
      "Estoy trabajando duro para traer nuevos ",
      "e increíbles proyectos. ¡No puedo esperar para ",
      "desvelárselos todos pronto!",
    ],
    colorBg: "orangeBg",
    colorTxt: "orangeTxt",
    image: false,
    id: 20,
    key: 6,
    float: "pointer-events-none",
    linkP: false,
    linkG: false,
    modalKey: 106,
    status: false,
    colorStatus: false,
  },
];

export { projects2 };
