const projects = [
  {
    name: "SOFTWARE",
    title: "GLEAM AI",
    creation: [
      { key: 1, language: "JavaScript" },
      { key: 2, language: "React JS" },
      { key: 3, language: "Next JS" },
    ],
    description:
      "Gleam AI is a platform that brings together the most popular artificial intelligence tools. Using the OpenAI and ReplicateAI APIs here you can find all the best AIs in one place.",
    colorBg: "gleamBg",
    colorTxt: "gleamTxt",
    image: "gleam cursor-pointer transition-all shadow-lg",
    id: 20,
    key: 3,
    float: false,
    linkP: "https://gleam-wine.vercel.app/",
    linkG: "https://github.com/Basso-23/Gleam-AI",
    modalKey: 103,
    status: "online",
    colorStatus: "bg-[#1ef758] glowOnline",
  },
  {
    name: "OTHERS",
    title: "PORTFOLIO",
    creation: [
      { key: 1, language: "JavaScript" },
      { key: 2, language: "React JS" },
      { key: 3, language: "Next JS" },
    ],
    description:
      "This is my portfolio, in where I showcase all my projects and also you can know me and my skills little bit better.",
    colorBg: "portfolioBg",
    colorTxt: "portfolioTxt",
    image: "portfolio cursor-pointer transition-all shadow-lg",
    id: 30,
    key: 1,
    float: false,
    linkP: "https://www.carlosbaso.com/",
    linkG: "https://github.com/Basso-23/Portfolio-Portafolio",
    modalKey: 101,
    status: "online",
    colorStatus: "bg-[#1ef758] glowOnline",
  },
  {
    name: "WEB DESIGN",
    title: false,
    creation: [
      { key: 1, language: "JavaScript" },
      { key: 2, language: "React JS" },
      { key: 3, language: "Next JS" },
    ],
    description: [
      "I'm working hard behind the scenes to bring you ",
      "new amazings projects! I can't wait ",
      "to unveil all of them to you soon!",
    ],
    colorBg: "greenBg",
    colorTxt: "greenTxt",
    image: false,
    id: 10,
    key: 2,
    float: "pointer-events-none",
    linkP: false,
    linkG: false,
    modalKey: 102,
    status: false,
    colorStatus: false,
  },
  {
    name: "OTHERS",
    title: false,
    creation: [
      { key: 1, language: "JavaScript" },
      { key: 2, language: "React JS" },
      { key: 3, language: "Next JS" },
    ],
    description: [
      "I'm working hard behind the scenes to bring you ",
      "new amazings projects! I can't wait ",
      "to unveil all of them to you soon!",
    ],
    colorBg: "yellowBg",
    colorTxt: "yellowTxt",
    image: false,
    id: 30,
    key: 4,
    float: "pointer-events-none",
    linkP: false,
    linkG: false,
    modalKey: 104,
    status: false,
    colorStatus: false,
  },
  {
    name: "WEB DESIGN",
    title: false,
    creation: [
      { key: 1, language: "JavaScript" },
      { key: 2, language: "React JS" },
      { key: 3, language: "Next JS" },
    ],
    description: [
      "I'm working hard behind the scenes to bring you ",
      "new amazings projects! I can't wait ",
      "to unveil all of them to you soon!",
    ],
    colorBg: "greenBg",
    colorTxt: "greenTxt",
    image: false,
    id: 10,
    key: 5,
    float: "pointer-events-none",
    linkP: false,
    linkG: false,
    modalKey: 105,
    status: false,
    colorStatus: false,
  },
  {
    name: "SOFTWARE",
    title: false,
    creation: [
      { key: 1, language: "JavaScript" },
      { key: 2, language: "React JS" },
      { key: 3, language: "Next JS" },
    ],
    description: [
      "I'm working hard behind the scenes to bring you ",
      "new amazings projects! I can't wait ",
      "to unveil all of them to you soon!",
    ],
    colorBg: "orangeBg",
    colorTxt: "orangeTxt",
    image: false,
    id: 20,
    key: 6,
    float: "pointer-events-none",
    linkP: false,
    linkG: false,
    modalKey: 106,
    status: false,
    colorStatus: false,
  },
];

export { projects };
