const projects2 = [
  {
    name: "DISEÑO WEB",
    title: "Próximamente...",
    description: [
      "Estoy trabajando duro para traer nuevos ",
      "e increíbles proyectos. ¡No puedo esperar para ",
      "desvelárselos todos pronto!",
    ],
    colorBg: "greenBg",
    colorTxt: "greenTxt",
    id: 10,
    key: 1,
    delay: 0.2,
  },
  {
    name: "SOFTWARE",
    title: "Próximamente...",
    description: [
      "Estoy trabajando duro para traer nuevos ",
      "e increíbles proyectos. ¡No puedo esperar para ",
      "desvelárselos todos pronto!",
    ],
    colorBg: "orangeBg",
    colorTxt: "orangeTxt",
    id: 20,
    key: 1,
    delay: 0.4,
  },
  {
    name: "OTROS",
    title: "Próximamente...",
    description: [
      "Estoy trabajando duro para traer nuevos ",
      "e increíbles proyectos. ¡No puedo esperar para ",
      "desvelárselos todos pronto!",
    ],
    colorBg: "yellowBg",
    colorTxt: "yellowTxt",
    id: 30,
    key: 1,
    delay: 0.6,
  },
  {
    name: "OTROS",
    title: "Próximamente...",
    description: [
      "Estoy trabajando duro para traer nuevos ",
      "e increíbles proyectos. ¡No puedo esperar para ",
      "desvelárselos todos pronto!",
    ],
    colorBg: "yellowBg",
    colorTxt: "yellowTxt",
    id: 30,
    key: 1,
    delay: 0.8,
  },
  {
    name: "DISEÑO WEB",
    title: "Próximamente...",
    description: [
      "Estoy trabajando duro para traer nuevos ",
      "e increíbles proyectos. ¡No puedo esperar para ",
      "desvelárselos todos pronto!",
    ],
    colorBg: "greenBg",
    colorTxt: "greenTxt",
    id: 10,
    key: 1,
    delay: 1,
  },
  {
    name: "SOFTWARE",
    title: "Próximamente...",
    description: [
      "Estoy trabajando duro para traer nuevos ",
      "e increíbles proyectos. ¡No puedo esperar para ",
      "desvelárselos todos pronto!",
    ],
    colorBg: "orangeBg",
    colorTxt: "orangeTxt",
    id: 20,
    key: 1,
    delay: 1.2,
  },
];

export { projects2 };
